genmove.so: main.cpp BetaElephant.cpp eleeye/pregen.cpp eleeye/position.cpp eleeye/genmoves.cpp 
	g++ -o genmove.so main.cpp BetaElephant.cpp eleeye/pregen.cpp eleeye/position.cpp eleeye/genmoves.cpp -lboost_python -lpython2.7 -I /usr/include/python2.7/ -shared
