genmove.so: genmove.cpp ../mcts-ucci/BetaElephant.cpp ../mcts-ucci/eleeye/pregen.cpp ../mcts-ucci/eleeye/position.cpp ../mcts-ucci/eleeye/genmoves.cpp 
	g++ -o genmove.so genmove.cpp ../mcts-ucci/BetaElephant.cpp ../mcts-ucci/eleeye/pregen.cpp ../mcts-ucci/eleeye/position.cpp ../mcts-ucci/eleeye/genmoves.cpp -lboost_python -lpython3.5 -I /usr/include/python3.5/ -shared
