genmove.so: genmove.cpp ../mcts-xboard/BetaElephant.cpp ../mcts-xboard/eleeye/pregen.cpp ../mcts-xboard/eleeye/position.cpp ../mcts-xboard/eleeye/genmoves.cpp 
	g++ -o genmove.so genmove.cpp ../mcts-xboard/BetaElephant.cpp ../mcts-xboard/eleeye/pregen.cpp ../mcts-xboard/eleeye/position.cpp ../mcts-xboard/eleeye/genmoves.cpp -lboost_python -lpython3.5 -I /usr/include/python3.5/ -shared -fPIC
