genmove.so: genmove.cpp ../mcts-xboard/BetaElephant.cpp ../mcts-xboard/eleeye/pregen.cpp ../mcts-xboard/eleeye/position.cpp ../mcts-xboard/eleeye/genmoves.cpp 
	g++ -o genmove.so genmove.cpp ../mcts-xboard/BetaElephant.cpp ../mcts-xboard/eleeye/pregen.cpp ../mcts-xboard/eleeye/position.cpp ../mcts-xboard/eleeye/genmoves.cpp -lboost_python-py34 -I /usr/include/python3.4/ -shared -fPIC
